name: "Release"

on:
  push:
    branches:
      - 'release/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  analyze:
    name: Static code analysis
    runs-on: windows-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Tag current commit
        shell: bash
        run: |
          version="${GITHUB_REF#refs/heads/release/}"
          git tag "${version}"
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          dotnet tool install minver-cli --global
          dotnet tool restore
          $version = minver -t v
          $productVersion,$prerelease = $version -split '-',2
          echo "Detected product version: $productVersion"
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"Testably_Testably.Architecture.Rules" /o:"testably" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /v:"$productVersion" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          dotnet tool install --global dotnet-coverage
          dotnet restore -s 'nuget.config'
          dotnet build --no-incremental /p:NetCoreOnly=True --configuration "Release"
          dotnet-coverage collect 'dotnet test --no-build' -f xml  -o 'coverage.xml'
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

  test-macos:
    name: Test (MacOS)
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Tag current commit
        shell: bash
        run: |
          version="${GITHUB_REF#refs/heads/release/}"
          git tag "${version}"
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
      - name: Build solution
        run: dotnet build /p:NetCoreOnly=True --configuration "Release"
      - name: Run tests
        run: dotnet test --no-build

  test-ubuntu:
    name: Test (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Tag current commit
        shell: bash
        run: |
          version="${GITHUB_REF#refs/heads/release/}"
          git tag "${version}"
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
      - name: Build solution
        run: dotnet build /p:NetCoreOnly=True --configuration "Release"
      - name: Run tests
        run: dotnet test --no-build

  test-windows:
    name: Test (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Tag current commit
        shell: bash
        run: |
          version="${GITHUB_REF#refs/heads/release/}"
          git tag "${version}"
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
      - name: Build solution
        run: dotnet build /p:NetCoreOnly=True --configuration "Release"
      - name: Run tests
        run: dotnet test --no-build

  test-net-framework:
    name: Test (.NET Framework)
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Tag current commit
        shell: bash
        run: |
          version="${GITHUB_REF#refs/heads/release/}"
          git tag "${version}"
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
      - name: Build solution
        run: msbuild.exe Testably.Architecture.Rules.sln /p:NetFrameworkOnly=True /p:platform="Any CPU" /p:configuration="Release" -t:restore,build -p:RestorePackagesConfig=true
      - name: Run tests
        run: vstest.console.exe .\Build\Tests\Testably.Architecture.Rules.Tests\net48\Testably.Architecture.Rules.Tests.dll

  stryker-ubuntu:
    name: Analyze quality of unit test coverage with .NET Stryker (Ubuntu)
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
      - name: Install .NET Stryker
        shell: bash
        run: |
          dotnet tool install dotnet-stryker --tool-path ../tools
      - name: Analyze Testably.Architecture.Rules
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
        shell: bash
        run: |
          cd Tests
          ../../tools/dotnet-stryker -f ../.github/stryker/Stryker.Config.json -v "${GITHUB_REF#refs/heads/}" -r "Dashboard" -r "cleartext"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    needs: [analyze, test-macos, test-ubuntu, test-windows, test-net-framework]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Tag current commit
        id: tag
        shell: bash
        run: |
          version="${GITHUB_REF#refs/heads/release/}"
          git tag "${version}"
          git push origin "${version}"
          echo "release_version=${version}" >> "$GITHUB_OUTPUT"
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
      - name: Prepare README.md
        shell: bash
        run: |
          for f in "README.md"
          do
            echo "Processing $f" # always double quote "$f" filename
            # do something on $f
            version="${GITHUB_REF#refs/heads/release/}"
            # Remove the codacy badge as it is not aligned to the release
            grep -v "Codacy Badge" "./$f" > "./$f.backup" && mv "./$f.backup" "./$f"
            # Change status badges to display explicit version
            sed -i -e "s/branch=main/branch=release%2F${version}/g" "./$f"
            sed -i -e "s/Testably.Architecture.Rules%2Fmain/Testably.Architecture.Rules%2Frelease%2F${version}/g" "./$f"
            sed -i -e "s/Testably.Architecture.Rules%2Fmain/Testably.Architecture.Rules%2Frelease%2F${version}/g" "./$f"
            sed -i -e "s/Testably.Architecture.Rules\/main)/Testably.Architecture.Rules\/release\/${version})/g" "./$f"
            # Add absolute path to example section
            sed -i -e 's/\(Examples\/README.md\)/https:\/\/github.com\/Testably\/Testably.Architecture.Rules\/blob\/main\/Examples\/README.md/g' "./$f"
          done
      - name: Build
        run: dotnet build --configuration "Release"
      - name: Publish
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.tag.outputs.release_version }}
          tag_name: ${{ steps.tag.outputs.release_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true

  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    needs: [deploy, stryker-ubuntu]
    steps:
      - name: Comment relevant issues and pull requests
        uses: apexskier/github-release-commenter@v1.3.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: |
            This is addressed in release {release_link}.
          label-template: |
            state: released
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Delete release branch
        shell: bash
        run: |
          version="${GITHUB_REF#refs/heads/release/}"
          git push origin -d "refs/heads/release/${version}"
